// const GENERATE_INVOICE = 'GENERATE_INVOICE';
export const SHOW_LOADING_MODAL = 'SHOW_LOADING_MODAL';
export const INVOICE_CALCULATION_SUCCESS = 'INVOICE_CALCULATION_SUCCESS';
export const INVOICE_CALCULATION_FAIL = 'INVOICE_CALCULATION_FAIL';
export const VALIDATION_ERROR = 'VALIDATION_ERROR'
